all: zad1 pk_init pk_kons pk_prod 

zad1: zad1.c
	gcc zad1.c -o zad1 -lrt

pk_init: pk_init.c
	gcc pk_init.c -o pk_init -lrt -lpthread

pk_kons: pk_kons.c
	gcc pk_kons.c -o pk_kons -lrt -lpthread

pk_prod: pk_prod.c
	gcc pk_prod.c -o pk_prod -lrt -lpthread
