all: init producent konsument zad2

init: init.c msg.h
	gcc init.c -o init -lrt

producent: producent.c
	gcc producent.c -o producent -lrt
	
konsument: konsument.c
	gcc konsument.c -o konsument -lrt
	
zad2: pierwsza_zad2 zad2.c
	gcc zad2.c -o zad2 -lrt
    
pierwsza_zad2: pierwsza_zad2.c
	gcc pierwsza_zad2.c -o pierwsza_zad2 -lrt
