all: zad1 zad2 zad3 zad4 pot pierwsza

zad1: pot zad1.c
	gcc zad1.c -o zad1

zad2: pot zad2.c
	gcc zad2.c -o zad2

zad3: pot zad3.c
	gcc zad3.c -o zad3

zad4: pierwsza zad4.c
	gcc zad4.c -o zad4

pot: pot.c
	gcc pot.c -o pot

pierwsza: pierwsza.c
	gcc pierwsza.c -o pierwsza

