all: zad1 zad2 zad3

zad1: pierwsza_zad1 zad1.c
	gcc zad1.c -o zad1
	
zad2: pierwsza_zad2 zad2.c
	gcc zad2.c -o zad2

zad3: zad3.c
	gcc zad3.c -o zad3

pierwsza_zad1: pierwsza_zad1.c
	gcc pierwsza_zad1.c -o pierwsza_zad1

pierwsza_zad2: pierwsza_zad2.c
	gcc pierwsza_zad2.c -o pierwsza_zad2

